CFLAGS=  -g -Wall -std=c99

reciever:
	$(CC) $(CFLAGS) -o rcv reciever.c

sender:
	$(CC) $(CFLAGS) -o sndr sender.c

test:
	$(CC) $(CFLAGS) -o test ProductivityTest.c

clean:
	rm -rf *.o snd* rcv* test*